#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | Yan-ho [ WE ONLY DO WHAT IS NECESSARY ]
// +----------------------------------------------------------------------
// | Copyright (c) 2017 http://www.yanho.vip All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yanho < 812580240@qq.com >
// +----------------------------------------------------------------------

// 定义应用目录
define('APP_PATH', __DIR__ . '/app/');
// define('BIND_MODULE','admin');
// 定义版本号
define('TPLAY_VERSION', '1.3.3');
//重定义扩展类库目录
define('EXTEND_PATH', __DIR__ . '/extend/');
//重定义第三方类库目录
define('VENDOR_PATH', __DIR__ . '/vendor/');
// 加载框架引导文件
require __DIR__.'/thinkphp/console.php';